# This file configures the analyzer for the example app.
# For more information, see: https://dart.dev/guides/language/analysis-options

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Additional rules for example code clarity
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: false  # Allow print statements in example code